# NOTE: this is only needed on vanilla Kubernetes; On OpenShift, the Operator Lifecycle Manager (OLM) creates the service automatically
apiVersion: v1
kind: Service
metadata:
  name: istio-operator-service
  namespace: istio-operator
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 11999
  selector:
    name: istio-operator
  type: ClusterIP
